# Generated by Django 4.1.7 on 2023-03-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('vendor', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('handle', models.SlugField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('template_suffix', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('published_scope', models.CharField(max_length=255)),
                ('tags', models.TextField(blank=True)),
                ('admin_graphql_api_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('inventory_policy', models.CharField(max_length=255)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fulfillment_service', models.CharField(max_length=255)),
                ('inventory_management', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255, null=True)),
                ('option2', models.CharField(max_length=255, null=True)),
                ('option3', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('taxable', models.BooleanField()),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('grams', models.IntegerField()),
                ('image_id', models.BigIntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('weight_unit', models.CharField(max_length=255)),
                ('inventory_item_id', models.BigIntegerField()),
                ('inventory_quantity', models.IntegerField()),
                ('old_inventory_quantity', models.IntegerField()),
                ('requires_shipping', models.BooleanField()),
                ('admin_graphql_api_id', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.BigIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.BigIntegerField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('alt', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('src', models.URLField()),
                ('variant_ids', models.JSONField()),
                ('admin_graphql_api_id', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.BigIntegerField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('alt', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('src', models.URLField()),
                ('variant_ids', models.JSONField()),
                ('admin_graphql_api_id', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
    ]
