# Generated by Django 4.1.7 on 2023-03-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptionvalues',
            name='option_id',
        ),
        migrations.AddField(
            model_name='productoptionvalues',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.productoption'),
        ),
    ]
