# Generated by Django 4.1.7 on 2023-03-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_createproduct_createproductvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.createproduct'),
        ),
        migrations.AlterField(
            model_name='createproductimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.createproduct'),
        ),
        migrations.AlterField(
            model_name='createproductoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.createproduct'),
        ),
        migrations.AlterField(
            model_name='createproductoptionvalues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.createproduct'),
        ),
        migrations.AlterField(
            model_name='createproductvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.createproduct'),
        ),
    ]
