# Generated by Django 4.1.7 on 2023-03-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_createproductimage_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createproductvariant',
            old_name='name',
            new_name='title',
        ),
    ]
