# Generated by Django 4.1.7 on 2023-03-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_name_createproductvariant_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproductoptionvalues',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.createproductoption'),
        ),
    ]
