# Generated by Django 4.1.7 on 2023-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_createproductoptionvalues_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_updated_status',
            field=models.BooleanField(default=True),
        ),
    ]
