# Generated by Django 4.1.7 on 2023-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='use_it',
            field=models.BooleanField(default=False),
        ),
    ]
